### PR TITLE
Moved the metadata into setup.cfg

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by guysv** [comment]
Hi, thanks for the pull request, but what is the rationale behind the change? is setup.py deprecated?

**Comment by KOLANICH** [comment]
I personally deprecate it. In fact there is a deep reason why `setup.cfg` and later `pyproject.toml` were created. Metadata must not be executable. It is obvious. If it is not obvious, see this: https://github.com/mschwager/0wned https://www.zdnet.com/article/twelve-malicious-python-libraries-found-and-removed-from-pypi/

**Comment by guysv** [comment]
Oh well, in the name of security :)
By the way, I see setup.py is not entirely removed, and setup.cfg is lacking the `data_files` field.
why's that?

**Comment by KOLANICH** [comment]
>I see setup.py is not entirely removed

We cannot currently fully remove it. But even if we cannot fully remove it, `setup.cfg` can be parsed without executing code and is easier to audit. And when we are able to fully remove it, we will have the metadata already declarative and moved.

>setup.cfg is lacking the data_files field. why's that?

You glob data files, I have not changed that, so it is still in `setup.py`.

**Comment by guysv** [comment]
all right. ill merge it. but don't expect a new release for it, as pypi provides wheels anyway.
thanks again for the patch!

**Comment by KOLANICH** [comment]
>but don't expect a new release for it,

I don't use releases, I usually install packages directly from their git repos :)

**Pull request merged**
