### PR TITLE
Fixed the version of `setuptools`. Earlier ones don't properly use `pyproject.toml`

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by guysv** [comment]
well, I don't want to force a setuptools version. especially if older versions used to work.
whats wrong with upgrading setuptools on your own in case you need it?

**Comment by KOLANICH** [comment]
We use `pyproject.toml` interface to `setuptools_scm`. It requires it be triggered. But earlier versions of `setuptools` don't trigger the stuff described in `pyproject.toml`. Without later setuptools the version won't be captured from git.

IMHO requiring a higher version of setuptools is not a big problem. I personally use versions from `master` branch, that's why the problem was masked for me. But on Travis for some other packages I saw errors, troubleshooting has revealed I have to upgrade setuptools.

**Comment by guysv** [comment]
For the record, im kinda against integrating every new fancy schmancy python packaging tool into my repos. It has its bloat, and after a couple of years with python i'm sure changes won't last for long. I allowed pyproject.toml into the tree thinking it won't effect the work cycle of current users (which is, well, me).

That said, I see setuptools 44 still supports python 2, so I don't reasons not to use it.

**Comment by KOLANICH** [comment]
Thanks.

**Pull request merged**
